import numpy as np
import argparse

# Get data file and info to update
parser = argparse.ArgumentParser(description='Script tp prepare data generated by Adam, to be on the right format for analysis.')
parser.add_argument('-f', '--data_file', type=str, help='File to prepare.')
parser.add_argument('-header', type=str, help='New file header.')
parser.add_argument('-val_ft', help='New value to assign to fake/trash events.')
args = parser.parse_args()

# Chosen file
data_file = args.data_file

# New header
new_header = args.header

# Old and new val_FT
old_val_FT = -1
new_val_FT = float(args.val_ft)

# Get data and change val_FT
data = np.loadtxt(data_file)
data[data.T[0]==old_val_FT] = np.ones(len(data[0])) * new_val_FT

# New file to put data
new_data_file = f"data/adam_clean/{data_file.split('/')[-1]}"

# Write new data file
np.savetxt(new_data_file, data, fmt='%s', header=new_header)

print('Created file:', new_data_file)